file_format: "1"
id: dactylsygnus
name: DactylSygnus
type: shield
url: https://github.com/juhakaup/keyboards/tree/main/Cygnus%20v0.5
requires: [pro_micro]
features:
  - keys
siblings:
  - dactylsygnus_left
  - dactylsygnus_right